name: deploy

on:
  workflow_call:
    inputs:
      deploymentEnvironment:
        required: true
        type: string
      deploymentRegion:
        required: true
        type: string
      deploymentEntity:
        required: true
        type: string
      resourceGroupName:
        required: true
        type: string
    secrets:
      AZURE_CLIENT_ID:
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_SUBSCRIPTION_ID:
        required: true

jobs:
  validate:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v3
     - uses: azure/login@v1
       name: Sign in to Azure
       with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
     - if: inputs.deploymentEnvironment != 'Production'
       uses: azure/arm-deploy@v1
       name: Run preflight validation
       with:
         deploymentName: ${{ github.run_number }}
         scope: resourcegroup
         resourceGroupName: ${{ inputs.resourceGroupName }}
         template: ./deploy/resources.bicep
         parameters: > 
          ./deploy/parameters/resources.${{ inputs.deploymentEnvironment }}.bicepparam 
          deploymentRegion=${{ inputs.deploymentRegion }}
          deploymentEnvironment=${{ inputs.deploymentEnvironment }}
          deploymentEntity=${{ inputs.deploymentEntity }}
         deploymentMode: Validate 

  preview:
    runs-on: ubuntu-latest
    needs: [validate]
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      name: Run what-if
      with:
        failOnStdErr: false
        scope: resourcegroup
        resourceGroupName: ${{ inputs.resourceGroupName }}
        template: ./deploy/resources.bicep
        parameters: > 
          ./deploy/parameters/resources.${{ inputs.deploymentEnvironment }}.bicepparam 
          deploymentRegion=${{ inputs.deploymentRegion }}
          deploymentEnvironment=${{ inputs.deploymentEnvironment }}
          deploymentEntity=${{ inputs.deploymentEntity }}
        additionalArguments: --what-if

  deploy:
    needs: [validate,preview]
    environment: ${{ inputs.deploymentEnvironment }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: azure/login@v1
      name: Sign in to Azure
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - uses: azure/arm-deploy@v1
      id: deploys
      name: Deploy Bicep file
      with:
        failOnStdErr: false
        deploymentName: ${{ github.run_number }}
        scope: resourcegroup
        resourceGroupName: ${{ inputs.resourceGroupName }}
        template: ./deploy/resources.bicep
        parameters: > 
          ./deploy/parameters/resources.${{ inputs.deploymentEnvironment }}.bicepparam 
          deploymentRegion=${{ inputs.deploymentRegion }}
          deploymentEnvironment=${{ inputs.deploymentEnvironment }}
          deploymentEntity=${{ inputs.deploymentEntity }}