name: lint

on:
  workflow_call:
    inputs:
      fileName:
        required: true
        type: string

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Lint code
      run: |
        az bicep build --file ${{ inputs.fileName}}