name: deploy-cloud-kitchen-core-infra
concurrency: cloud-kitchen-company

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:

  # Lint the Bicep file.
  lint-resource-group:
    uses: ./.github/workflows/lint.yml
    with:
      fileName: deploy/resourcegroups.bicep
  
  lint-resources:
    uses: ./.github/workflows/lint.yml
    with:
      fileName: deploy/resources.bicep

  # Deploy to the dev environment.
  deploy-resource-group-devv:
    uses: ./.github/workflows/deploy-resourcegroup.yml
    needs: lint-resource-group
    with:
      deploymentEnvironment: DEVV
      deploymentRegion: uksouth
      deploymentEntity: core
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID}}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    

  job2:
    runs-on: ubuntu-latest
    needs: deploy-resource-group-devv
    steps:
    - run: echo ${{needs.deploy-resource-group-devv.outputs.resourceGroupName}}

  # # Deploy to the dev environment.
  # deploy-resource-devv:
  #   uses: ./.github/workflows/deploy-resources.yml
  #   needs:  deploy-resource-group-devv
  #   with:
  #     deploymentEnvironment: DEVV
  #     deploymentRegion: uksouth
  #     deploymentEntity: core
  #     resourceGroupName: ${{needs.deploy-resource-group-devv.outputs.resourceGroupName}}
  #   secrets:
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID}}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}